apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxhelmtest
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginxhelmtest
  replicas: 1
  template:
    metadata:
      labels:
        app: nginxhelmtest
    spec:
      containers:
      - name: nginxhelmtest
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 80
